version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: backend-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=verySafePassword
      - POSTGRES_USER=root
      - POSTGRES_DB=backend
